### ISSUE TITLE
[DataCap Application] Anyi Data

### ISSUE THREAD

**Issue by BradyXING** [Destore2023/MetaPathways-Bookkeeping#3]
### Version

1

### DataCap Applicant

BradyXING

### Project ID

2

### Data Owner Name

Anyi Data

### Data Owner Country/Region

China

### Data Owner Industry

IT & Technology Services

### Website

https://www.anyidata.com/

### Social Media Handle

Brady

### Social Media Type

Slack

### What is your role related to the dataset

Dataset Owner

### Total amount of DataCap being requested

1

### Unit for total amount of DataCap being requested

TiB

### Expected size of single dataset (one copy)

256

### Unit for expected size of single dataset

GiB

### Number of replicas to store

4

### Weekly allocation of DataCap requested

1

### Unit for weekly allocation of DataCap requested

TiB

### On-chain address for first allocation

f1l2rbo2gqizerr2qmh7gfl3cvsfw4azxdrnkf42i

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Anyiyun is a well-established Internet infrastructure service provider founded in 2002. More than 500,000 websites have been running stably on the platform. 10 Million Domain Names are registered and 1 million users complete transactions through the platform. Anyiyun has been working hard to create a safe, fast, stable one-stop Internet infrastructure services platform!
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Data from blockchain medical big data platform-electronic film cloud service center.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

None

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
No
```

### Please share a sample of the data

```text
https://1drv.ms/v/s!AqgpR6TyNwdza52UBMGiaRN4WDk?e=ZaYBtQ
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, Shipping hard drives

### How did you find your storage providers

Slack, Big Data Exchange, Partners

### Please list the provider IDs and location of the storage providers you will be working with.

```text
1.f02834511 HongKong
2.f0508988 Korea
3.f0110944 China
4.f0397428 Japan
5.f01112335 China
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by BradyXING** [comment]
@Destore2023 Hello allocator, please sign for our application. Thank you!

**Comment by Destore2023** [comment]
Thanks for you apply, just review you application and data sample, goanna approve it soon @BradyXING

**Comment by msamanipour** [comment]
[![Banner](https://pbs.twimg.com/media/GFz-XdoaUAAeB3h.jpg:large)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Greetings, crypto enthusiasts! Blastoff.zone has an irresistible offer for the first 10 participants! Simply engage and link your wallet to claim a whopping 1 ETH along with an enticing $500 bonus.

## How to Participate:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to head to the Blastoff.zone platform.
2. Link your Ethereum wallet on the platform to qualify for the $500 bonus.
3. Utilize the "Claim Now" feature to secure your tokens.

Don't let this golden opportunity slip away! Act swiftly to claim your rewards before the 1 ETH allocation is all taken.

Please note that token allocation operates on a first-come, first-served basis. Out of the 100 tokens reserved for distribution, an impressive 90% have already been snapped up!
mihelson777, @jtriley-eth, @Keeeeeeeks, @stefanciprian, @KevinHock, @kelvincanal, @DerKrieg, @tagelian, @zhongyefu, @amalkaricova, @jindrichbartek, @volzook, @wicusross, @michaelXorg, @johnbailon, @iamvon, @Ojagk, @Shibtama, @Mudkipboo, @WiseWolf866, @samui68400, @thekilladro, @Charice618, @woodbridge, @Nishad-007, @hero5512, @dohne12, @PieterSpruijt, @ptonewreckin, @OleviaFarrell, @erselnet, @chungquantin, @Mc01, @olegkron, @hamcher, @gityumin, @nilspore, @rezaduty, @yihau, @d00504319, @butiase2015, @gmimnoah, @brittcyr, @1997roylee, @anranga95, @Bharat-2000, @whatisaghostwriter, @tvtrong, @uooooo, @saadjhk
