### ISSUE TITLE
[DataCap Application] EOT Web Archive Dataset

### ISSUE THREAD

**Issue by francis024** [Destore2023/MetaPathways-Bookkeeping#6]
### Version

1

### DataCap Applicant

Francis

### Project ID

/

### Data Owner Name

EOT

### Data Owner Country/Region

United States

### Data Owner Industry

Government

### Website

https://eotarchive.org/

### Social Media Handle

https://twitter.com/eotarchive

### Social Media Type

Twitter

### What is your role related to the dataset

Data Preparer

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

642TiB

### Number of replicas to store

8

### Weekly allocation of DataCap requested

256TiB

### On-chain address for first allocation

f1dhjmvrgazw2njbov6qprzyh7aawhaponpsxmwbi

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
We're a individual group of web 3. We wanna deeply experience the functionality of the filecoin ecosystem by storing real data.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The End of Term Web Archive (EOT) captures and saves U.S. Government websites at the end of presidential administrations. The EOT has thus far preserved websites from administration changes in 2008, 2012, 2016, and 2020. Data from these web crawls have been made openly available in several formats in this dataset.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

United States

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
Use lotus
We prepare data and turn it into car files.
```

### Please share a sample of the data

```text
aws s3 ls --no-sign-request s3://eotarchive/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

Shipping hard drives, Lotus built-in data transfer

### How did you find your storage providers

Slack, Big Data Exchange

### Please list the provider IDs and location of the storage providers you will be working with.

```text
1. f02247136, Beijing
2. f01344987, HongKong
3. f02128256, Toronto
4. f01843994, Dulles
5. f01844118, NewYork
```

### How do you plan to make deals to your storage providers

Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by francis024** [comment]
Hello allocator @Destore2023 , I'm Francis, the same handle as slack. I will leave some words to you.

Wait for your reply!

**Comment by Destore2023** [comment]
![image](https://github.com/Destore2023/MetaPathways-Bookkeeping/assets/46444977/849e0c76-019f-4068-a10b-3fc71d04707b)
Could anyone help to fix this error?

**Comment by Destore2023** [comment]
checker:manualTrigger

**Comment by Destore2023** [comment]
LGTM, willing to support the next round manually.

**Comment by filecoin-watchdog** [comment]
checker:manualTrigger

**Comment by francis024** [comment]
Hello sir @Destore2023 , as your request, I've updated the list of sps I've worked with so far.
1. f03089385, NewYork
2. f03089826, Dulles
3. f03090976, Dulles
4. f03106356, Dulles
5. f03087482, Ashburn

**Comment by Destore2023** [comment]
checker:manualTrigger

**Comment by Destore2023** [comment]
Stop allocations and close this application due to some sps' low retrieval rates.
@francis024 If you want to continue your storage, you should find new sps and reapply an new application. Thank you.
