### ISSUE TITLE
[DataCap Application] NIH NCBI SRA on AWS

### ISSUE THREAD

**Issue by Nixonfb1** [Destore2023/MetaPathways-Bookkeeping#8]
### Version

1

### DataCap Applicant

Nixon

### Project ID

1

### Data Owner Name

NLM

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://www.ncbi.nlm.nih.gov/

### Social Media Handle

https://x.com/NLM_NIH

### Social Media Type

Twitter

### What is your role related to the dataset

Data Preparer

### Total amount of DataCap being requested

10PiB

### Expected size of single dataset (one copy)

1.56PiB

### Number of replicas to store

6

### Weekly allocation of DataCap requested

512TiB

### On-chain address for first allocation

f1k3m2kmv4z33wwgqueddz2f6scnxojeif3ekvmkq

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
This is a public dataset on aws. As a data preparer, we offer assistance to sp in storing meaningful data on filecoin.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The Sequence Read Archive (SRA), produced by the National Center for Biotechnology Information (NCBI) at the National Library of Medicine (NLM) at the National Institutes of Health (NIH), stores raw DNA sequencing data and alignment information from high-throughput sequencing platforms. The SRA provides open access to these biological sequence data to support the research community's efforts to enhance reproducibility and make new discoveries by comparing data sets. Buckets in this registry contain public SRA data in the original (user submitted) format from select high value and newly-released studies as well as all public-access SRA formatted ETL+BQS data. Also included is all SRA metadata that can be leveraged for attribute-based data discovery.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

Hong Kong

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
We used to learn how to use Lotus and we'll use it to prepare data.
```

### Please share a sample of the data

```text
s3://sra-pub-src-1/
s3://sra-pub-src-2/
s3://sra-pub-run-odp/
s3://sra-pub-metadata-us-east-1/sra/metadata/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives, Lotus built-in data transfer

### How did you find your storage providers

Slack

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f01841131 HONGKONG
f02244750 LONDON
f01807908 MADRID
f01879772 HONGKONG
f02363999 SINGAPORE
```

### How do you plan to make deals to your storage providers

Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Nixonfb1** [comment]
Hello allocator, please review the application.

**Comment by Destore2023** [comment]
Please fill in this form to complete your information. 
https://www.wenjuan.com/s/qAVFfuN/

**Comment by Nixonfb1** [comment]
@Destore2023 Hello allocator, we have completed the form.

**Comment by Nixonfb1** [comment]
If you need more information, please let us know.

**Comment by Destore2023** [comment]
Thanks for your submission, We will review it ASAP.
![screenshot](https://github.com/Destore2023/MetaPathways-Bookkeeping/assets/46444977/342e8491-cad4-4a43-b6c7-6315e478aae8)

Once the review is complete, datacap will be allocated in your address. Please follow the community rules and distribute datacap properly.

**Comment by filecoin-watchdog** [comment]
checker:manualTrigger

**Comment by Destore2023** [comment]
checker:manualTrigger

**Comment by Destore2023** [comment]
Stop allocations and close this application due to some sps' low retrieval rates.
@Nixonfb1 If you want to continue your storage, you should find new sps and reapply an new application. Thank you.
